baseURL: 'https://fran-cool.netlify.app/'
title: fran.cool
languageCode: en-us
defaultContentLanguage: en
taxonomies:
  page: pages
  works: works

menu:
  main:
  - identifier: i038rh390h
    name: "Works"
    title: "works"
    url: "/#works"
    weight: 20
  - identifier: 3u9r0f30no
    name: "About"
    title: "about"
    url: "/#about"
    weight: 30

params:
  logo: https://res.cloudinary.com/dikhrro6y/image/upload/v1664819388/fran.cool-black.svg

mediaTypes:
  text/x-netlify:
    suffixes: []

outputFormats:
  redirects:
    baseName: _redirects
    isPlainText: true
    mediaType: text/x-netlify
    ugly: true

outputs:
  home:
  - HTML
  - redirects