baseURL = 'https://fran-cool.netlify.app/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = "fran.cool"


# Languages
[Languages.en]
  languageName = "En"
  languageCode = "en-us"
  contentDir = "content"
  weight = 1
  mark = "EN"


[taxonomies]
  page= "pages"
  works = "works"
