# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
site_url: https://fran-cool.netlify.app/
show_preview_links: true
publish_mode: editorial_workflow
editor:
  preview: true
locale: "en"

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

media_library:
  name: cloudinary
  config:
    cloud_name: dikhrro6y
    api_key: 462899953829293

# collections configuration
collections:
  - name: "global"
    label: "Global Settings"
    files:
      - file: "data/start-screen.yml"
        label: "Start Screen"
        name: "start-screen"
        fields:
          [
            {
              label: "Title Top",
              name: "title-top",
              widget: string,
              default: "fran is",
            },
            {
              label: "Title Bottom",
              name: "title-bottom",
              widget: string,
              default: "COOL",
            },
            { label: "Image", name: "image", widget: "image" },
          ]
      - file: "data/header.yml"
        label: "Header"
        name: "header"
        fields:
          [
            { label: "Logo", name: "logo", widget: "image" },
            {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Link Text", name: "text", widget: "string" },
                  { label: "URL", name: "text", widget: "string" },
                ],
            },
          ]
      - file: "data/footer.yml"
        label: "Footer"
        name: "header"
        fields:
          [
            {
              label: "Marquee Text",
              name: "marquee",
              widget: "string",
              default: "Let’s get to work!\t🛠",
            },
            {
              label: "Email Address",
              name: "email",
              widget: "string",
              default: "hey@fran.cool",
            },
            {
              label: "Signature",
              name: "signature",
              widget: "string",
              default: "Fran, Creative Overthinker",
            },
            {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Link Text", name: "text", widget: "string" },
                  { label: "URL", name: "text", widget: "string" },
                ],
            },
          ]
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      - name: "modules"
        label: "modules"
        widget: "list"
        types:
          - name: "richtext"
            label: "Rich Text"
            widget: object
            summary: "{{fields.text | truncate(20, '***')}}"
            fields:
              - name: "text"
                label: "Text"
                widget: markdown
                default: "Nisi magna id ad in proident dolore incididunt enim velit cupidatat amet et occaecat consequat."
                modes:
                  - rich_text
                  - raw
                sanitize_preview: true
          - name: "works"
            label: "Works"
            widget: object
            summary: "{{fields.title}}"
            fields:
              - name: "title"
                label: "Title"
                widget: string
                default: "WORKS"
              - name: "button"
                title: "Button Text"
                widget: string
                default: "see more"
          - name: "about"
            label: "About"
            widget: object
            summary: "{{fields.title}}"
            fields:
              - name: "title"
                label: "Title"
                widget: string
                default: "ABOUT"
              - name: "text"
                label: "Text"
                widget: markdown
                default: "Nisi magna id ad in proident dolore incididunt enim velit cupidatat amet et occaecat consequat."
                modes:
                  - rich_text
                  - raw
                sanitize_preview: true
              - name: "image"
                label: "Image"
                widget: "image"
  - name: "works"
    label: "Works"
    folder: "content/works"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Date", name: "date", widget: "datetime" },
        { label: "Cover Image", name: "image", widget: "image" },
        {
          label: "Summary",
          name: "summary",
          widget: "text",
          hint: "Used for listing pages and meta description",
        },
        {
          label: "Content",
          name: "modules",
          widget: "list",
          types:
            [
              {
                label: "Paragraph",
                name: "paragraph",
                widget: object,
                summary: "{{fields.title}}",
                fields:
                  [
                    { name: "title", label: "Title", widget: string },
                    {
                      name: "text",
                      label: "Text",
                      widget: markdown,
                      default: "Nisi magna id ad in proident dolore incididunt enim velit cupidatat amet et occaecat consequat.",
                      modes: ["rich_text", "raw"],
                      sanitize_preview: true,
                    },
                  ],
              },
              {
                label: "Images",
                name: "images",
                widget: object,
                summary: "{{fields[0].fields.image}}",
                fields:
                  [
                    {
                      name: "images",
                      label: "Images",
                      widget: list,
                      summary: "{{fields.image}}",
                      field: {label: Image, name: image, widget: image}
                    },
                  ],
              },
            ],
        },
        { label: "Project Link", name: "link", widget: "string" }
      ]
